/turtlesim:
  ros__parameters:
    background_b: 50
    background_g: 186
    background_r: 169
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
